// Code generated by goyacc -o ansi-c.yacc.go -v ansi-c.yacc.output -p YC ansi-c.y. DO NOT EDIT.

//line ansi-c.y:2
package ansi_c

import __yyfmt__ "fmt"

//line ansi-c.y:2

//line ansi-c.y:5
type YCSymType struct {
	yys int
}

const IDENTIFIER = 57346
const CONSTANT = 57347
const STRING_LITERAL = 57348
const SIZEOF = 57349
const PTR_OP = 57350
const INC_OP = 57351
const DEC_OP = 57352
const LEFT_OP = 57353
const RIGHT_OP = 57354
const LE_OP = 57355
const GE_OP = 57356
const EQ_OP = 57357
const NE_OP = 57358
const AND_OP = 57359
const OR_OP = 57360
const MUL_ASSIGN = 57361
const DIV_ASSIGN = 57362
const MOD_ASSIGN = 57363
const ADD_ASSIGN = 57364
const SUB_ASSIGN = 57365
const LEFT_ASSIGN = 57366
const RIGHT_ASSIGN = 57367
const AND_ASSIGN = 57368
const XOR_ASSIGN = 57369
const OR_ASSIGN = 57370
const TYPE_NAME = 57371
const TYPEDEF = 57372
const EXTERN = 57373
const STATIC = 57374
const AUTO = 57375
const REGISTER = 57376
const CHAR = 57377
const SHORT = 57378
const INT = 57379
const LONG = 57380
const SIGNED = 57381
const UNSIGNED = 57382
const FLOAT = 57383
const DOUBLE = 57384
const CONST = 57385
const VOLATILE = 57386
const VOID = 57387
const STRUCT = 57388
const UNION = 57389
const ENUM = 57390
const ELLIPSIS = 57391
const CASE = 57392
const DEFAULT = 57393
const IF = 57394
const ELSE = 57395
const SWITCH = 57396
const WHILE = 57397
const DO = 57398
const FOR = 57399
const GOTO = 57400
const CONTINUE = 57401
const BREAK = 57402
const RETURN = 57403

var YCToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"CONSTANT",
	"STRING_LITERAL",
	"SIZEOF",
	"PTR_OP",
	"INC_OP",
	"DEC_OP",
	"LEFT_OP",
	"RIGHT_OP",
	"LE_OP",
	"GE_OP",
	"EQ_OP",
	"NE_OP",
	"AND_OP",
	"OR_OP",
	"MUL_ASSIGN",
	"DIV_ASSIGN",
	"MOD_ASSIGN",
	"ADD_ASSIGN",
	"SUB_ASSIGN",
	"LEFT_ASSIGN",
	"RIGHT_ASSIGN",
	"AND_ASSIGN",
	"XOR_ASSIGN",
	"OR_ASSIGN",
	"TYPE_NAME",
	"TYPEDEF",
	"EXTERN",
	"STATIC",
	"AUTO",
	"REGISTER",
	"CHAR",
	"SHORT",
	"INT",
	"LONG",
	"SIGNED",
	"UNSIGNED",
	"FLOAT",
	"DOUBLE",
	"CONST",
	"VOLATILE",
	"VOID",
	"STRUCT",
	"UNION",
	"ENUM",
	"ELLIPSIS",
	"CASE",
	"DEFAULT",
	"IF",
	"ELSE",
	"SWITCH",
	"WHILE",
	"DO",
	"FOR",
	"GOTO",
	"CONTINUE",
	"BREAK",
	"RETURN",
	"'('",
	"')'",
	"'['",
	"']'",
	"'.'",
	"','",
	"'&'",
	"'*'",
	"'+'",
	"'-'",
	"'~'",
	"'!'",
	"'/'",
	"'%'",
	"'<'",
	"'>'",
	"'^'",
	"'|'",
	"'?'",
	"':'",
	"'='",
	"';'",
	"'{'",
	"'}'",
}

var YCStatenames = [...]string{}

const YCEofCode = 1
const YCErrCode = 2
const YCInitialStackSize = 16

//line yacctab:1
var YCExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const YCPrivate = 57344

const YCLast = 1280

var YCAct = [...]int{
	72, 95, 94, 296, 145, 6, 233, 93, 121, 75,
	149, 41, 47, 5, 5, 226, 133, 123, 116, 11,
	48, 49, 50, 115, 201, 140, 10, 144, 139, 308,
	51, 294, 32, 301, 83, 120, 160, 147, 239, 57,
	138, 239, 347, 254, 119, 117, 169, 307, 168, 300,
	8, 118, 255, 122, 126, 125, 306, 128, 55, 238,
	160, 61, 58, 63, 114, 240, 134, 110, 64, 122,
	160, 154, 150, 302, 199, 246, 161, 184, 159, 62,
	102, 135, 126, 125, 315, 157, 209, 210, 165, 203,
	33, 213, 214, 204, 316, 341, 160, 31, 158, 215,
	192, 194, 126, 196, 216, 217, 70, 28, 222, 195,
	142, 39, 32, 18, 19, 20, 21, 24, 25, 22,
	23, 29, 30, 17, 36, 37, 35, 171, 174, 175,
	176, 177, 178, 179, 180, 181, 182, 183, 32, 185,
	223, 60, 59, 313, 272, 340, 228, 234, 200, 207,
	208, 31, 327, 218, 326, 29, 30, 154, 245, 150,
	247, 225, 243, 299, 142, 231, 224, 229, 248, 345,
	227, 252, 228, 160, 325, 241, 253, 31, 156, 141,
	256, 31, 319, 343, 317, 269, 126, 160, 318, 142,
	142, 173, 219, 142, 142, 262, 33, 249, 250, 251,
	126, 126, 293, 31, 292, 126, 126, 126, 126, 126,
	126, 126, 126, 126, 126, 126, 126, 126, 126, 126,
	258, 259, 265, 274, 285, 286, 287, 273, 200, 271,
	126, 125, 200, 57, 270, 134, 9, 126, 125, 290,
	134, 291, 126, 125, 304, 51, 298, 309, 142, 283,
	284, 275, 276, 303, 225, 231, 281, 282, 305, 277,
	278, 279, 280, 314, 267, 257, 266, 32, 56, 42,
	32, 126, 312, 189, 190, 191, 160, 311, 320, 310,
	142, 160, 268, 160, 220, 134, 160, 291, 221, 137,
	272, 136, 228, 202, 126, 125, 143, 324, 53, 271,
	52, 45, 4, 4, 126, 125, 134, 234, 328, 166,
	322, 332, 333, 334, 32, 164, 150, 126, 338, 331,
	329, 163, 236, 237, 162, 33, 339, 187, 227, 186,
	228, 188, 31, 148, 342, 205, 206, 344, 198, 211,
	212, 146, 288, 346, 235, 67, 348, 264, 335, 337,
	143, 263, 167, 2, 3, 38, 79, 111, 112, 101,
	78, 98, 99, 77, 76, 73, 242, 67, 131, 54,
	129, 232, 33, 67, 34, 143, 143, 202, 27, 143,
	143, 28, 12, 13, 14, 15, 16, 18, 19, 20,
	21, 24, 25, 22, 23, 29, 30, 17, 36, 37,
	35, 26, 80, 81, 84, 7, 85, 86, 87, 88,
	89, 90, 91, 92, 113, 40, 172, 96, 100, 261,
	104, 105, 106, 107, 108, 109, 97, 103, 1, 0,
	0, 0, 0, 0, 143, 82, 46, 155, 0, 0,
	0, 0, 79, 111, 112, 101, 28, 98, 99, 0,
	0, 0, 18, 19, 20, 21, 24, 25, 22, 23,
	29, 30, 17, 36, 37, 35, 143, 28, 12, 13,
	14, 15, 16, 18, 19, 20, 21, 24, 25, 22,
	23, 29, 30, 17, 36, 37, 35, 0, 80, 81,
	84, 0, 85, 86, 87, 88, 89, 90, 91, 92,
	113, 0, 230, 0, 0, 43, 104, 105, 106, 107,
	108, 109, 79, 111, 112, 101, 0, 98, 99, 0,
	0, 82, 46, 69, 0, 0, 0, 28, 12, 13,
	14, 15, 16, 18, 19, 20, 21, 24, 25, 22,
	23, 29, 30, 17, 36, 37, 35, 65, 79, 111,
	112, 101, 71, 98, 99, 0, 0, 0, 80, 81,
	84, 0, 85, 86, 87, 88, 89, 90, 91, 92,
	113, 0, 0, 0, 0, 0, 104, 105, 106, 107,
	108, 109, 46, 0, 79, 111, 112, 101, 0, 98,
	99, 82, 46, 244, 80, 81, 84, 0, 85, 86,
	87, 88, 89, 90, 91, 92, 113, 0, 0, 0,
	0, 0, 104, 105, 106, 107, 108, 109, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 82, 46, 153,
	80, 81, 84, 0, 85, 86, 87, 88, 89, 90,
	91, 92, 113, 0, 0, 0, 0, 0, 104, 105,
	106, 107, 108, 109, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 82, 46, 28, 12, 13, 14, 15,
	16, 18, 19, 20, 21, 24, 25, 22, 23, 29,
	30, 17, 36, 37, 35, 0, 0, 0, 0, 0,
	127, 111, 112, 101, 0, 98, 99, 0, 0, 0,
	0, 0, 127, 111, 112, 101, 0, 98, 99, 0,
	0, 0, 0, 0, 0, 28, 0, 0, 64, 0,
	46, 18, 19, 20, 21, 24, 25, 22, 23, 29,
	30, 17, 36, 37, 35, 127, 111, 112, 101, 0,
	98, 99, 74, 0, 0, 0, 0, 0, 113, 44,
	0, 0, 0, 0, 104, 105, 106, 107, 108, 109,
	113, 0, 0, 0, 0, 0, 104, 105, 106, 107,
	108, 109, 127, 111, 112, 101, 0, 98, 99, 0,
	0, 0, 151, 330, 66, 0, 68, 0, 0, 127,
	111, 112, 101, 113, 98, 99, 0, 0, 0, 104,
	105, 106, 107, 108, 109, 0, 0, 0, 152, 0,
	28, 0, 0, 0, 0, 151, 18, 19, 20, 21,
	24, 25, 22, 23, 29, 30, 17, 36, 37, 35,
	113, 0, 0, 0, 0, 0, 104, 105, 106, 107,
	108, 109, 0, 0, 32, 0, 0, 113, 0, 0,
	0, 82, 0, 104, 105, 106, 107, 108, 109, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 170, 28,
	12, 13, 14, 15, 16, 18, 19, 20, 21, 24,
	25, 22, 23, 29, 30, 17, 36, 37, 35, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 227, 295, 228, 0, 0, 0, 0, 31,
	28, 12, 13, 14, 15, 16, 18, 19, 20, 21,
	24, 25, 22, 23, 29, 30, 17, 36, 37, 35,
	32, 0, 127, 111, 112, 101, 0, 98, 99, 0,
	0, 0, 0, 272, 295, 228, 127, 111, 112, 101,
	31, 98, 99, 0, 0, 28, 12, 13, 14, 15,
	16, 18, 19, 20, 21, 24, 25, 22, 23, 29,
	30, 17, 36, 37, 35, 127, 111, 112, 101, 0,
	98, 99, 0, 0, 0, 0, 0, 0, 33, 0,
	113, 336, 0, 0, 0, 31, 104, 105, 106, 107,
	108, 109, 0, 0, 113, 0, 0, 321, 0, 0,
	104, 105, 106, 107, 108, 109, 127, 111, 112, 101,
	0, 98, 99, 0, 0, 0, 0, 0, 0, 127,
	111, 112, 101, 113, 98, 99, 297, 0, 0, 104,
	105, 106, 107, 108, 109, 127, 111, 112, 101, 0,
	98, 99, 0, 0, 0, 0, 0, 127, 111, 112,
	101, 0, 98, 99, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 113, 260, 0, 0, 0, 0,
	104, 105, 106, 107, 108, 109, 0, 113, 0, 0,
	124, 0, 0, 104, 105, 106, 107, 108, 109, 127,
	111, 112, 101, 113, 98, 99, 0, 0, 0, 104,
	105, 106, 107, 108, 109, 197, 0, 0, 0, 0,
	0, 104, 105, 106, 107, 108, 109, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 132, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 193, 0, 0,
	0, 0, 0, 104, 105, 106, 107, 108, 109, 28,
	12, 13, 14, 15, 16, 18, 19, 20, 21, 24,
	25, 22, 23, 29, 30, 17, 36, 37, 35, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 130, 28, 12, 13, 14, 15, 16,
	18, 19, 20, 21, 24, 25, 22, 23, 29, 30,
	17, 36, 37, 35, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 323, 28,
	12, 13, 14, 15, 16, 18, 19, 20, 21, 24,
	25, 22, 23, 29, 30, 17, 36, 37, 35, 289,
	28, 12, 13, 14, 15, 16, 18, 19, 20, 21,
	24, 25, 22, 23, 29, 30, 17, 36, 37, 35,
}

var YCPact = [...]int{
	926, 926, -1000, -1000, -1000, 28, 498, 1231, 1231, 1231,
	310, 236, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 112, -1000, 134, 58, 57, -1000, -1000, -1000, -1000,
	-4, 636, -1000, 498, -1000, -1000, 438, 28, -1000, -1000,
	-1000, 236, 1025, 1140, 112, -1000, -1000, 226, -44, 781,
	337, -47, -1000, 134, 731, 498, -1000, -1000, -1000, -1000,
	544, 352, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 4,
	1041, -3, -1000, -7, 262, 259, 253, 580, 247, 348,
	-35, -37, 785, -1000, -1000, 109, 59, 265, 1095, 1095,
	1041, 1053, 321, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-5, -1000, -1000, 686, 11, 25, 320, 73, 328, 21,
	30, -1000, -14, 88, -1000, -1000, -1000, -1000, 129, 221,
	-1000, 41, -1000, -1000, 108, -1000, -1000, -1000, 781, 417,
	-1000, 263, 781, 781, -26, -1000, -17, 337, -1000, -1000,
	-1000, 731, -1000, -1000, -1000, -1000, 508, 580, -6, 580,
	1041, -1000, 1041, 1041, 1041, 116, 768, -40, -1000, -1000,
	-1000, -31, 1041, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 1041, 1041, 1041, 1012, 347, 343,
	-1000, -1000, -1000, 1041, -1000, -1000, -1000, 686, 1041, 1041,
	219, 122, 82, 1041, 1041, 1041, 1041, 1041, 1041, 1041,
	1041, 1041, 1041, 1041, 1041, 1041, 1041, 1041, -1000, -1000,
	-1000, 338, 1210, -1000, -1000, 266, 140, 840, 971, 78,
	-1000, -1000, -34, -1000, -8, 1041, -1000, -1000, -1000, 337,
	1041, -29, -38, -1000, -1000, -1000, 580, -1000, -1000, 216,
	214, 209, 81, 768, -1000, -1000, -1000, 321, 3, 29,
	-1000, 121, -1000, -1000, -1000, 119, -5, 11, -1000, 1041,
	-1000, 228, 881, 25, 320, 73, 73, 328, 328, 328,
	328, 21, 21, 30, 30, -1000, -1000, -1000, -1000, -1000,
	-1000, 140, 942, 1175, 111, -1000, 91, -1000, 87, -1000,
	-1000, 263, 1041, -1000, -1000, -1000, -1000, -1000, 698, -1000,
	580, 580, 580, 1041, 928, 1041, -1000, -1000, 1041, -1000,
	-1000, -1000, 80, -1000, 32, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 281, -1000, -1000, 120, 580, 106, -1000, -1000,
	-1000, -1000, 580, -41, -1000, 580, -1000, -1000, -1000,
}

var YCPgo = [...]int{
	0, 428, 427, 34, 426, 419, 7, 1, 418, 8,
	24, 35, 44, 51, 45, 18, 23, 64, 67, 80,
	417, 2, 416, 17, 301, 12, 415, 405, 50, 236,
	269, 5, 10, 401, 378, 374, 28, 25, 179, 371,
	6, 27, 4, 26, 19, 3, 370, 369, 368, 16,
	31, 15, 366, 0, 365, 742, 9, 364, 363, 360,
	106, 505, 353, 354,
}

var YCR1 = [...]int{
	0, 2, 2, 2, 2, 4, 4, 4, 4, 4,
	4, 4, 4, 5, 5, 7, 7, 7, 7, 7,
	7, 8, 8, 8, 8, 8, 8, 9, 9, 11,
	11, 11, 11, 12, 12, 12, 13, 13, 13, 14,
	14, 14, 14, 14, 15, 15, 15, 16, 16, 17,
	17, 18, 18, 19, 19, 20, 20, 21, 21, 6,
	6, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 3, 3, 23, 24, 24, 25, 25, 25,
	25, 25, 25, 26, 26, 30, 30, 27, 27, 27,
	27, 27, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 33, 33, 33, 35, 35, 36,
	36, 37, 38, 38, 38, 38, 39, 39, 40, 40,
	40, 34, 34, 34, 41, 41, 42, 42, 29, 29,
	31, 31, 44, 44, 44, 44, 44, 44, 44, 43,
	43, 43, 43, 47, 47, 45, 45, 48, 48, 49,
	49, 49, 46, 46, 10, 10, 50, 50, 50, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 32, 32,
	32, 52, 52, 53, 53, 53, 53, 53, 53, 54,
	54, 54, 55, 55, 55, 55, 61, 61, 60, 60,
	56, 56, 57, 57, 57, 58, 58, 58, 58, 59,
	59, 59, 59, 59, 1, 1, 62, 62, 63, 63,
	63, 63,
}

var YCR2 = [...]int{
	0, 1, 1, 1, 3, 1, 4, 3, 4, 3,
	3, 2, 2, 1, 3, 1, 2, 2, 2, 2,
	4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
	3, 3, 3, 1, 3, 3, 1, 3, 3, 1,
	3, 3, 3, 3, 1, 3, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 1, 3, 1, 5, 1,
	3, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 1, 2, 3, 1, 2, 1,
	2, 1, 2, 1, 3, 1, 3, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 5, 4, 2, 1, 1, 1,
	2, 3, 2, 1, 2, 1, 1, 3, 1, 2,
	3, 4, 5, 2, 1, 3, 1, 3, 1, 1,
	2, 1, 1, 3, 4, 3, 4, 4, 3, 1,
	2, 2, 3, 1, 2, 1, 3, 1, 3, 2,
	2, 1, 1, 3, 1, 2, 1, 1, 2, 3,
	2, 3, 3, 4, 2, 3, 3, 4, 1, 3,
	4, 1, 3, 1, 1, 1, 1, 1, 1, 3,
	4, 3, 2, 3, 3, 4, 1, 2, 1, 2,
	1, 2, 5, 7, 5, 5, 7, 6, 7, 3,
	2, 2, 2, 3, 1, 2, 1, 1, 4, 3,
	3, 2,
}

var YCChk = [...]int{
	-1000, -1, -62, -63, -24, -25, -31, -27, -28, -29,
	-43, -44, 30, 31, 32, 33, 34, 45, 35, 36,
	37, 38, 41, 42, 39, 40, -33, -34, 29, 43,
	44, 69, 4, 62, -35, 48, 46, 47, -62, 83,
	-26, -31, -30, -61, -55, -24, 84, -25, -25, -25,
	-25, -44, 64, 62, -47, -43, -29, -31, 4, 84,
	84, 4, 83, 67, 82, -61, -55, -24, -55, 85,
	-60, -61, -53, -54, -55, -56, -57, -58, -59, 4,
	50, 51, 83, -3, 52, 54, 55, 56, 57, 58,
	59, 60, 61, -6, -21, -7, -20, -4, 9, 10,
	-8, 7, -19, -2, 68, 69, 70, 71, 72, 73,
	-18, 5, 6, 62, -17, -16, -15, -14, -13, -12,
	-11, -9, -31, -23, 65, -21, -7, 4, -45, -46,
	63, -48, 4, -49, -25, -43, -29, 63, 84, -36,
	-37, -38, -28, -29, -41, -42, 4, 84, -30, -32,
	-6, 84, -55, 85, -53, 85, -60, 81, -23, 81,
	67, 83, 62, 62, 62, -53, 62, 4, 83, 83,
	83, -3, -22, 82, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 18, 80, 64, 62, 66, 8,
	9, 10, -7, 62, -7, -9, -7, 62, 17, 79,
	-3, -10, -38, 78, 68, 15, 16, 76, 77, 13,
	14, 11, 12, 70, 71, 69, 74, 75, 65, 63,
	63, 67, 67, -31, -50, -43, -51, 62, 64, -36,
	85, -37, -39, -40, -31, 81, -38, -38, 85, 67,
	82, -41, -52, -32, 85, -53, 81, -53, -6, -3,
	-3, -3, 55, -56, 83, 83, -6, -19, -3, -3,
	63, -5, -6, 4, 4, -10, -18, -17, 63, 63,
	-50, -43, 62, -16, -15, -14, -14, -13, -13, -13,
	-13, -12, -12, -11, -11, -9, -9, -9, 4, 49,
	-49, -51, 64, 62, -50, 63, -45, 65, -23, 85,
	83, 67, 81, -23, -42, -23, 85, 85, 67, -53,
	63, 63, 63, 62, -56, 81, 65, 63, 67, 63,
	-9, 65, -23, 63, -45, 63, 63, 65, -40, -23,
	85, -32, -53, -53, -53, -3, 63, -3, -21, -6,
	65, 63, 53, 63, -53, 63, -53, 83, -53,
}

var YCDef = [...]int{
	0, -2, 204, 206, 207, 0, 0, 77, 79, 81,
	0, 131, 87, 88, 89, 90, 91, 92, 93, 94,
	95, 96, 97, 98, 99, 100, 101, 102, 103, 128,
	129, 139, 132, 0, 0, 0, 107, 108, 205, 75,
	0, 85, 83, 0, 211, 186, 0, 0, 78, 80,
	82, 130, 0, 0, 140, 141, 143, 0, 106, 0,
	0, 123, 76, 0, 0, 0, 209, 187, 210, 182,
	0, 0, 188, 173, 174, 175, 176, 177, 178, 1,
	0, 0, 190, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 72, 59, 27, 57, 15, 0, 0,
	0, 0, 55, 5, 21, 22, 23, 24, 25, 26,
	53, 2, 3, 0, 51, 49, 47, 44, 39, 36,
	33, 29, 85, 0, 135, 74, 27, 1, 0, 0,
	138, 145, 152, 147, 151, 142, 144, 133, 0, 0,
	109, 0, 113, 115, 0, 124, 126, 0, 84, 86,
	168, 0, 208, 183, 189, 184, 0, 0, 0, 0,
	0, 191, 0, 0, 0, 0, 0, 0, 200, 201,
	202, 0, 0, 61, 62, 63, 64, 65, 66, 67,
	68, 69, 70, 71, 0, 0, 0, 0, 0, 0,
	11, 12, 16, 0, 17, 18, 19, 0, 0, 0,
	0, 0, 154, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 134, 136,
	137, 0, 0, 149, 150, 156, 157, 0, 0, 0,
	105, 110, 0, 116, 118, 0, 112, 114, 121, 0,
	0, 0, 0, 171, 185, 179, 0, 181, 73, 0,
	0, 0, 0, 0, 199, 203, 60, 56, 0, 0,
	7, 0, 13, 9, 10, 0, 54, 52, 4, 0,
	155, 156, 0, 50, 48, 45, 46, 40, 41, 42,
	43, 37, 38, 34, 35, 30, 31, 32, 153, 146,
	148, 158, 0, 0, 0, 164, 0, 160, 0, 104,
	111, 0, 0, 119, 125, 127, 122, 169, 0, 180,
	0, 0, 0, 0, 0, 0, 6, 8, 0, 20,
	28, 162, 0, 166, 0, 159, 165, 161, 117, 120,
	170, 172, 192, 194, 195, 0, 0, 0, 58, 14,
	163, 167, 0, 0, 197, 0, 193, 196, 198,
}

var YCTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 73, 3, 3, 3, 75, 68, 3,
	62, 63, 69, 70, 67, 71, 66, 74, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 81, 83,
	76, 82, 77, 80, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 64, 3, 65, 78, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 84, 79, 85, 72,
}

var YCTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
}

var YCTok3 = [...]int{
	0,
}

var YCErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	YCDebug        = 0
	YCErrorVerbose = false
)

type YCLexer interface {
	Lex(lval *YCSymType) int
	Error(s string)
}

type YCParser interface {
	Parse(YCLexer) int
	Lookahead() int
}

type YCParserImpl struct {
	lval  YCSymType
	stack [YCInitialStackSize]YCSymType
	char  int
}

func (p *YCParserImpl) Lookahead() int {
	return p.char
}

func YCNewParser() YCParser {
	return &YCParserImpl{}
}

const YCFlag = -1000

func YCTokname(c int) string {
	if c >= 1 && c-1 < len(YCToknames) {
		if YCToknames[c-1] != "" {
			return YCToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func YCStatname(s int) string {
	if s >= 0 && s < len(YCStatenames) {
		if YCStatenames[s] != "" {
			return YCStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func YCErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !YCErrorVerbose {
		return "syntax error"
	}

	for _, e := range YCErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + YCTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := YCPact[state]
	for tok := TOKSTART; tok-1 < len(YCToknames); tok++ {
		if n := base + tok; n >= 0 && n < YCLast && YCChk[YCAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if YCDef[state] == -2 {
		i := 0
		for YCExca[i] != -1 || YCExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; YCExca[i] >= 0; i += 2 {
			tok := YCExca[i]
			if tok < TOKSTART || YCExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if YCExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += YCTokname(tok)
	}
	return res
}

func YClex1(lex YCLexer, lval *YCSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = YCTok1[0]
		goto out
	}
	if char < len(YCTok1) {
		token = YCTok1[char]
		goto out
	}
	if char >= YCPrivate {
		if char < YCPrivate+len(YCTok2) {
			token = YCTok2[char-YCPrivate]
			goto out
		}
	}
	for i := 0; i < len(YCTok3); i += 2 {
		token = YCTok3[i+0]
		if token == char {
			token = YCTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = YCTok2[1] /* unknown char */
	}
	if YCDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", YCTokname(token), uint(char))
	}
	return char, token
}

func YCParse(YClex YCLexer) int {
	return YCNewParser().Parse(YClex)
}

func (YCrcvr *YCParserImpl) Parse(YClex YCLexer) int {
	var YCn int
	var YCVAL YCSymType
	var YCDollar []YCSymType
	_ = YCDollar // silence set and not used
	YCS := YCrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	YCstate := 0
	YCrcvr.char = -1
	YCtoken := -1 // YCrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		YCstate = -1
		YCrcvr.char = -1
		YCtoken = -1
	}()
	YCp := -1
	goto YCstack

ret0:
	return 0

ret1:
	return 1

YCstack:
	/* put a state and value onto the stack */
	if YCDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", YCTokname(YCtoken), YCStatname(YCstate))
	}

	YCp++
	if YCp >= len(YCS) {
		nyys := make([]YCSymType, len(YCS)*2)
		copy(nyys, YCS)
		YCS = nyys
	}
	YCS[YCp] = YCVAL
	YCS[YCp].yys = YCstate

YCnewstate:
	YCn = YCPact[YCstate]
	if YCn <= YCFlag {
		goto YCdefault /* simple state */
	}
	if YCrcvr.char < 0 {
		YCrcvr.char, YCtoken = YClex1(YClex, &YCrcvr.lval)
	}
	YCn += YCtoken
	if YCn < 0 || YCn >= YCLast {
		goto YCdefault
	}
	YCn = YCAct[YCn]
	if YCChk[YCn] == YCtoken { /* valid shift */
		YCrcvr.char = -1
		YCtoken = -1
		YCVAL = YCrcvr.lval
		YCstate = YCn
		if Errflag > 0 {
			Errflag--
		}
		goto YCstack
	}

YCdefault:
	/* default state action */
	YCn = YCDef[YCstate]
	if YCn == -2 {
		if YCrcvr.char < 0 {
			YCrcvr.char, YCtoken = YClex1(YClex, &YCrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if YCExca[xi+0] == -1 && YCExca[xi+1] == YCstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			YCn = YCExca[xi+0]
			if YCn < 0 || YCn == YCtoken {
				break
			}
		}
		YCn = YCExca[xi+1]
		if YCn < 0 {
			goto ret0
		}
	}
	if YCn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			YClex.Error(YCErrorMessage(YCstate, YCtoken))
			Nerrs++
			if YCDebug >= 1 {
				__yyfmt__.Printf("%s", YCStatname(YCstate))
				__yyfmt__.Printf(" saw %s\n", YCTokname(YCtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for YCp >= 0 {
				YCn = YCPact[YCS[YCp].yys] + YCErrCode
				if YCn >= 0 && YCn < YCLast {
					YCstate = YCAct[YCn] /* simulate a shift of "error" */
					if YCChk[YCstate] == YCErrCode {
						goto YCstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if YCDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", YCS[YCp].yys)
				}
				YCp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if YCDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", YCTokname(YCtoken))
			}
			if YCtoken == YCEofCode {
				goto ret1
			}
			YCrcvr.char = -1
			YCtoken = -1
			goto YCnewstate /* try again in the same state */
		}
	}

	/* reduction by production YCn */
	if YCDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", YCn, YCStatname(YCstate))
	}

	YCnt := YCn
	YCpt := YCp
	_ = YCpt // guard against "declared and not used"

	YCp -= YCR2[YCn]
	// YCp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if YCp+1 >= len(YCS) {
		nyys := make([]YCSymType, len(YCS)*2)
		copy(nyys, YCS)
		YCS = nyys
	}
	YCVAL = YCS[YCp+1]

	/* consult goto table to find next state */
	YCn = YCR1[YCn]
	YCg := YCPgo[YCn]
	YCj := YCg + YCS[YCp].yys + 1

	if YCj >= YCLast {
		YCstate = YCAct[YCg]
	} else {
		YCstate = YCAct[YCj]
		if YCChk[YCstate] != -YCn {
			YCstate = YCAct[YCg]
		}
	}
	// dummy call; replaced with literal code
	switch YCnt {

	}
	goto YCstack /* stack new state and value */
}
